name: Run unit tests and create PR
on: [push]
jobs:
  test-and-pr:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.22"]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Create env file
        run: |
          touch .env
          echo TEST_PUBLIC_KEY=${{ secrets.TEST_PUBLIC_KEY }} >> .env
          echo TEST_SECRET_KEY=${{ secrets.TEST_SECRET_KEY }} >> .env
          echo TEST_ANONYMOUS_SECRET_KEY=${{ secrets.TEST_ANONYMOUS_SECRET_KEY }} >> .env
          echo TEST_ANONYMOUS_PUBLIC_KEY=${{ secrets.TEST_ANONYMOUS_PUBLIC_KEY }} >> .env

      - name: Test
        run: go test -v

      - name: Create Pull Request
        if: success() && github.ref != 'refs/heads/main'
        run: |
          gh pr create \
            -B main \
            -H ${{ github.ref_name }} \
            --title "Merge ${{ github.ref_name }} into main" \
            --body "Created by Github action after successful tests"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
